print("\tMasukkan Biodata")
nama = input("Nama\t\t\t: ")
nim = input("NIM\t\t\t: ")
kelasParalel = input("Kelas Paralel\t\t: ")
ttl = input("Tempat/Tanggal Lahir\t: ")
alamat = input("Alamat\t\t\t: ")
hobby = input("Hobby\t\t\t: ")
noHP = input("No HP\t\t\t: ")
print("\n\tBIODATA")
print("Nama\t\t\t: " + nama)
print("NIM\t\t\t: " + nim)
print("Kelas Paralel\t\t: " + kelasParalel)
print("Tempat/Tanggal Lahir\t: " + ttl)
print("Alamat\t\t\t: " + alamat)
print("Hobby\t\t\t: " + hobby)
print("No HP\t\t\t: " + noHP)